[storage]
raw = '/mnt/sync/voice-raw'  # where to import it to
meta = '/mnt/sync/voice-raw/.meta'
processed = '/mnt/sync/voice/unsorted'  # where to put processed files
processed_list = '/mnt/sync/voice/unsorted/.list'  # track what's processed
# example paths: voice-raw/2024-02-11/almond/190412.flac
# example paths: voice/unsorted/2024-02-11/tx660-tx650/1904n1-1905.d20.opus

[devices.a]
glob = 'REC_FILE/FOLDER01/*.wav'
prefer_channel = 'left'
# should be unique enough
drive.Id = 'SONY-IC-RECORDER-180E94E1007818'

[devices.b]
glob = 'REC_FILE/FOLDER01/*.wav'
prefer_channel = 'right'
# should be unique enough
drive.Id = 'SONY-IC-RECORDER-180E93A1001689'

[devices.g]
glob = 'VOICE/FOLDER0*/*.WAV'
  [devices.g.drive]
  # should be enough to detect the right thing
  Id = 'SONY-IC-RECORDER-01078CAFCF2B'
  # just to be super-specific
  CanPowerOff = true
  ConnectionBus = 'usb'
  Ejectable = true
  Model = 'IC RECORDER'
  Removable = true
  Revision = '3.00'
  Serial = '01078CAFCF2B'
  Vendor = 'SONY'
